### ISSUE TITLE
bug: Deleting a concept should redirect to `/concepts`

### ISSUE THREAD

**Issue by dipasqualew** [photion/web-admin#173]
**Describe the bug**
No point on staying on the page after deleting the concept.

**To Reproduce**
Go to a concept page. Press delete. Enjoy

**Expected behavior**
Page redirects the user to the list of all concepts, so that they can continue using the app.

**Comment by loiscodes** [comment]
I'll take this one

**Comment by dipasqualew** [comment]
> I'll take this one

Thanks! Just assign your PR to me once it is ready to be reviewed 🙂
