### ISSUE TITLE
bug: Creating a concept should update the page URL.

### ISSUE THREAD

**Issue by dipasqualew** [photion/web-admin#174]
**Describe the bug**
Create is done on `/concepts/new`; however, once the concept has been created and we are given its UUID, we are not redirect the user to `/concept/:uuid`. Therefore, refreshing the page prompts the user to create a new concept.

**To Reproduce**
1. Go to `/concepts/new`
2. Create a concept

**Expected behavior**
Creating the concept updates the url to `/concepts/:uuid`

**Comment by sahiljulka** [comment]
I would like to work on this one @dipasqualew

**Comment by dipasqualew** [comment]
Please @sahiljulka! I assigned the issue to you. Feel free to open a PR and I'll review it 🙂

**Comment by sahiljulka** [comment]
I have raised a PR
Kindly review once and revert if any test cases are required

**Comment by dipasqualew** [comment]
Closed via #190
