### ISSUE TITLE
feat: Tooltip component

### ISSUE THREAD

**Issue by dipasqualew** [photion/web-admin#188]
**Is your feature request related to a problem? Please describe.**
Often we want to display additional information about an element. It is helpful to trigger a tooltip with additional content.

**Describe the solution you'd like**
- [ ] The tooltip should look as common component tooltips: blackbox with an central arrow, white text;
- [ ] Should accept HTML (i.e. a `<slot />`)
- [ ] Should accept a prop for standard text (`<slot>` takes precedence)
- [ ] Should be aware of its own surroundings and be displayed in a convenient space (don't pop where it can't be fully displayed).

**Comment by yurianxdev** [comment]
I think we have two options:
1. Creating a **wrapper** component
2. Creating a **Vue directive**

What do you guys prefer?

**Comment by dipasqualew** [comment]
I'd prefer a component. I think it's more vue-like (Vue styleguide advised against them) and more extendable. Directives are often "black magic" that change the dom in unexpected ways.

Also, with a directive we won't be able to pass custom HTML (like making a part of the tooltip bold or italic).

What do you think?

**Comment by yurianxdev** [comment]
Agree. I think it would look like this:
```
<PhoTooltip>
  <template v-slot:default>
    <PhoButton></PhoButton>
  </template>
  <template v-slot:tooltip>
    This is a <strong>tooltip</strong>.
  </template>
</PhoTooltip>
```

How it seems to you?

**Comment by dipasqualew** [comment]
Let it accept an optional `tooltip` prop which is passed to the tooltip template by default, so we cover the most common scenario (tooltips are most likely going to be plain text). The rest of it totally makes sense, can't wait to have them everywhere 🙂

**Comment by dipasqualew** [comment]
@limoncella Could you move

```
- [ ] Should be aware of its own surroundings and be displayed in a convenient space (don't pop where it can't be fully displayed).
```

Into a new issue and link to this one?

Cheers

**Comment by limoncella** [comment]
Linked to #207
