### ISSUE TITLE
bug: Disabled button has cursor `pointer `

### ISSUE THREAD

**Issue by limoncella** [photion/web-admin#192]
**Describe the bug**
A disabled button has cursor `pointer`. 

**To Reproduce**
1. Go to https://admin.photion.app/services/googleDrive
2. Mouse over the "Coming Soon" button

**Expected behavior**
Cursor is not `pointer`, it is `default`.

**Comment by dipasqualew** [comment]
Thanks @limoncella, I have assigned you to the bug. Please feel free to assign me to the PR. Cheers
