### ISSUE TITLE
FontAwesome resources are not being loaded

### ISSUE THREAD

**Issue by yurianxdev** [photion/web-admin#88]
Due to an error `Failed to find a valid digest in the 'integrity' attribute for resource 'https://use.fontawesome.com/releases/v5.8.2/css/all.css'`, FontAwesome resource is not being loaded, apparently, the SHA code in `public/index.html` is not working.

I suggest adding FontAwesome locally anyways.
![Screen Shot 2020-09-28 at 11 54 49](https://user-images.githubusercontent.com/42949739/94462959-dcb21780-0181-11eb-81d5-6eaf8a28935b.png)

**Comment by dipasqualew** [comment]
I think the link was injected by the Vuetify plugin... The more I think about it... 🙂 

My preference would be to install FontAwesome as a package, so that it can be tree-shaken:
https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers
